# Generated by Django 4.1.9 on 2023-05-20 17:03

from django.db import migrations, models
import django.db.models.deletion
import django_extensions.db.fields


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="JobCategory",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name="ScholarshipCategory",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name="Scholarship",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "created",
                    django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name="created"),
                ),
                (
                    "modified",
                    django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name="modified"),
                ),
                ("title", models.CharField(max_length=255, verbose_name="title")),
                ("description", models.TextField(blank=True, null=True, verbose_name="description")),
                (
                    "slug",
                    django_extensions.db.fields.AutoSlugField(
                        blank=True, editable=False, populate_from="title", verbose_name="slug"
                    ),
                ),
                ("amount", models.IntegerField()),
                ("deadline", models.DateField()),
                ("apply_link", models.URLField()),
                ("active", models.BooleanField(default=False)),
                (
                    "category",
                    models.ForeignKey(
                        null=True, on_delete=django.db.models.deletion.SET_NULL, to="main.scholarshipcategory"
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Job",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "created",
                    django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name="created"),
                ),
                (
                    "modified",
                    django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name="modified"),
                ),
                ("title", models.CharField(max_length=255, verbose_name="title")),
                ("description", models.TextField(blank=True, null=True, verbose_name="description")),
                (
                    "slug",
                    django_extensions.db.fields.AutoSlugField(
                        blank=True, editable=False, populate_from="title", verbose_name="slug"
                    ),
                ),
                ("company_name", models.CharField(max_length=200)),
                (
                    "job_type",
                    models.CharField(
                        choices=[("part_time", "Part Time"), ("full_time", "Full Time")],
                        default="part_time",
                        max_length=20,
                    ),
                ),
                ("location", models.TextField()),
                ("salary_min", models.IntegerField(verbose_name="Min Salery")),
                ("salary_max", models.IntegerField(verbose_name="Max Salery")),
                ("apply_link", models.URLField()),
                ("active", models.BooleanField(default=False)),
                (
                    "category",
                    models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to="main.jobcategory"),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
