# Generated by Django 4.1.9 on 2023-05-23 16:55

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="jobcategory",
            options={"ordering": ("name",), "verbose_name": "Job Category", "verbose_name_plural": "Job Categories"},
        ),
        migrations.AlterModelOptions(
            name="scholarshipcategory",
            options={
                "ordering": ("name",),
                "verbose_name": "Scholarship Category",
                "verbose_name_plural": "Scholarship Categories",
            },
        ),
    ]
