# Generated by Django 4.1.9 on 2023-05-23 17:26

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0002_alter_jobcategory_options_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="job",
            name="deadline",
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
