# Generated by Django 4.1.9 on 2023-05-23 17:28

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0003_job_deadline"),
    ]

    operations = [
        migrations.AddField(
            model_name="job",
            name="hours",
            field=models.IntegerField(default=2, help_text="working hours per week"),
            preserve_default=False,
        ),
    ]
