# Generated by Django 4.1.9 on 2023-05-23 17:33

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0004_job_hours"),
    ]

    operations = [
        migrations.AddField(
            model_name="job",
            name="body",
            field=tinymce.models.HTMLField(default="dsfs"),
            preserve_default=False,
        ),
    ]
