# Generated by Django 4.1.9 on 2023-05-28 13:53

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0006_scholarship_body"),
    ]

    operations = [
        migrations.AlterField(
            model_name="scholarship",
            name="amount",
            field=models.CharField(max_length=100),
        ),
    ]
