# Generated by Django 4.1.9 on 2023-06-06 11:06

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0008_remove_job_body_remove_scholarship_body_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="jobcategory",
            name="name",
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name="scholarshipcategory",
            name="name",
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
