# Generated by Django 4.1.9 on 2023-06-06 13:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0010_alter_jobcategory_name_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="scholarship",
            name="category",
            field=models.ForeignKey(
                blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to="main.scholarshipcategory"
            ),
        ),
    ]
