# Generated by Django 4.1.9 on 2023-06-06 13:37

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0011_alter_scholarship_category"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="job",
            name="salary_max",
        ),
        migrations.RemoveField(
            model_name="job",
            name="salary_min",
        ),
        migrations.AddField(
            model_name="job",
            name="salery_range",
            field=models.CharField(default="2300-334", max_length=200, verbose_name="Salery Range"),
            preserve_default=False,
        ),
    ]
