# Generated by Django 4.1.9 on 2023-06-07 08:21

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0013_alter_job_hours"),
    ]

    operations = [
        migrations.AddField(
            model_name="job",
            name="full_job_description",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="job",
            name="job_type",
            field=models.CharField(
                choices=[("Part-time", "Part-time"), ("Full-time", "Full-time")], default="Part-time", max_length=20
            ),
        ),
    ]
