# Generated by Django 4.1.9 on 2023-06-07 08:50

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0015_remove_job_category_remove_job_created_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="job",
            name="company_name",
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
