# Generated by Django 4.1.9 on 2023-06-07 09:00

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0017_alter_job_salery_range"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="job",
            name="salery_range",
        ),
        migrations.AddField(
            model_name="job",
            name="salary_range",
            field=models.CharField(default="200-300", max_length=300, verbose_name="Salary Range"),
            preserve_default=False,
        ),
    ]
