# Generated by Django 4.1.9 on 2023-06-07 09:01

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0018_remove_job_salery_range_job_salary_range"),
    ]

    operations = [
        migrations.AlterField(
            model_name="job",
            name="full_job_description",
            field=models.TextField(blank=True, max_length=3000, null=True),
        ),
    ]
