# Generated by Django 4.1.9 on 2023-06-07 18:55

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0019_alter_job_full_job_description"),
    ]

    operations = [
        migrations.AlterField(
            model_name="job",
            name="company_name",
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
