# Generated by Django 4.1.9 on 2023-06-07 18:56

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0020_alter_job_company_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="job",
            name="company_name",
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name="job",
            name="full_job_description",
            field=models.TextField(blank=True, null=True),
        ),
    ]
