# Generated by Django 4.1.9 on 2023-06-07 19:04

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0021_alter_job_company_name_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="job",
            name="apply_link",
            field=models.URLField(max_length=500),
        ),
    ]
