# Generated by Django 4.1.9 on 2023-06-07 19:05

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0022_alter_job_apply_link"),
    ]

    operations = [
        migrations.AlterField(
            model_name="job",
            name="apply_link",
            field=models.CharField(max_length=1000),
        ),
    ]
