# Generated by Django 4.1.9 on 2023-06-08 05:27

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0023_alter_job_apply_link"),
    ]

    operations = [
        migrations.RenameField(
            model_name="job",
            old_name="deadline",
            new_name="expiration_date",
        ),
    ]
